name: build

on:
  push:
    tags: v.*.*

jobs:
  build:
      name: third_party
      runs-on: windows-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            submodules: recursive
        - name: Apply Boost Semaphore Patch
          working-directory: projects/boost/libs/interprocess
          run: git apply ../../../../patches/interprocess_semaphore.patch
          
        - name: Detect MSVC
          uses: ilammy/msvc-dev-cmd@v1
          with:
            arch: x86_64
        - name: Prepare Vulkan SDK
          uses: humbletim/install-vulkan-sdk@c2aa128094d42ba02959a660f03e0a4e012192f9
          with:
            version: 1.3.275.0
            cache: true
            
        - name: Configure
          run: cmake -S. -B_build/_Release -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=_build/_Install -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe

        - name: Build
          run: cmake --build _build/_Release -j4
  
        - name: Install
          run: cmake --install _build/_Release

        - name: Zip it up
          working-directory: _build/_Release
          run: |
            7z a psOff-3rd.zip .\install\* -xr!licenses
          
        - name: Create release
          uses: softprops/action-gh-release@v2
          with:
            prerelease: false
            name: psOff thirdparty ${{ github.ref_name }}
            files: _build/_Release/psOff-3rd.zip
